# Generated by Django 6.0.3 on 2026-06-19 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_companyproductprice'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='companyproductprice',
            new_name='prices_comp_product_d2997d_idx',
            old_name='prices_comp_product_c1f6d9_idx',
        ),
        migrations.RenameIndex(
            model_name='companyproductprice',
            new_name='prices_comp_company_803e34_idx',
            old_name='prices_comp_company_3ba05b_idx',
        ),
    ]
