# Generated by Django 6.0.3 on 2026-04-10 21:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='farm',
            constraint=models.UniqueConstraint(fields=('farmer', 'farm_name', 'district', 'subcounty', 'village'), name='unique_farm_per_farmer_location'),
        ),
    ]
