# Generated by Django 5.2.7 on 2026-05-22 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_offline_sync_and_farmactivity'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='farm',
            name='unique_farmer_farm_client_id',
        ),
        migrations.RemoveConstraint(
            model_name='farmactivity',
            name='unique_farmer_activity_client_id',
        ),
        migrations.RemoveConstraint(
            model_name='farmexpense',
            name='unique_farmer_expense_client_id',
        ),
        migrations.RemoveConstraint(
            model_name='harvestrecord',
            name='unique_farmer_harvest_client_id',
        ),
        migrations.RemoveConstraint(
            model_name='salesrecord',
            name='unique_farmer_sale_client_id',
        ),
        migrations.RenameIndex(
            model_name='farmactivity',
            new_name='farms_farma_farmer__4c588c_idx',
            old_name='farms_farma_farmer__664975_idx',
        ),
        migrations.RenameIndex(
            model_name='farmactivity',
            new_name='farms_farma_farmer__6653e3_idx',
            old_name='farms_farma_farmer__a4fe11_idx',
        ),
    ]
