# Generated by Django 5.2.7 on 2026-05-23 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_farm_projects_planner_profit_tracking'),
        ('farms', '0004_remove_farm_unique_farmer_farm_client_id_and_more'),
    ]

    operations = [
    ]
