# Generated by Django 6.0.3 on 2026-05-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0005_merge_20260523_1031'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='farmproject',
            name='unique_farmer_project_client_id',
        ),
        migrations.RemoveConstraint(
            model_name='projectinputrecord',
            name='unique_farmer_input_client_id',
        ),
        migrations.RemoveConstraint(
            model_name='projectplannedactivity',
            name='unique_farmer_plan_client_id',
        ),
        migrations.RemoveConstraint(
            model_name='projectrevenuerecord',
            name='unique_farmer_revenue_client_id',
        ),
        migrations.RenameIndex(
            model_name='farmproject',
            new_name='farms_farmp_farmer__a557d5_idx',
            old_name='farms_farmpr_farmer__status_idx',
        ),
        migrations.RenameIndex(
            model_name='farmproject',
            new_name='farms_farmp_farmer__2c2b6b_idx',
            old_name='farms_farmpr_farmer__ptype_idx',
        ),
        migrations.RenameIndex(
            model_name='farmproject',
            new_name='farms_farmp_farmer__57bf5d_idx',
            old_name='farms_farmpr_farmer__upd_idx',
        ),
        migrations.RenameIndex(
            model_name='projectinputrecord',
            new_name='farms_proje_farmer__49c09b_idx',
            old_name='farms_projinput_farmer_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='projectinputrecord',
            new_name='farms_proje_project_d4931d_idx',
            old_name='farms_projinput_project_date_idx',
        ),
        migrations.RenameIndex(
            model_name='projectplannedactivity',
            new_name='farms_proje_farmer__ce5c64_idx',
            old_name='farms_projpl_farmer__date_idx',
        ),
        migrations.RenameIndex(
            model_name='projectplannedactivity',
            new_name='farms_proje_project_4efbae_idx',
            old_name='farms_projpl_project_status_idx',
        ),
        migrations.RenameIndex(
            model_name='projectrevenuerecord',
            new_name='farms_proje_project_3d2f3f_idx',
            old_name='farms_projrev_project_date_idx',
        ),
    ]
