# Generated by Django 6.0.3 on 2026-06-19 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0008_production_batches'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productionbatch',
            new_name='farms_produ_farmer__04ecaa_idx',
            old_name='farms_produ_farmer__98df3a_idx',
        ),
        migrations.RenameIndex(
            model_name='productionbatch',
            new_name='farms_produ_project_ec08fd_idx',
            old_name='farms_produ_project_39b92f_idx',
        ),
    ]
